### ISSUE TITLE
white noise

### ISSUE THREAD

**Issue by resom78** [melchor629/chromecaster-gui#3]
Hi,

I tried your app which looks very nice!
And the functionnalities are just perfect except the fact it doesn't play sounds!
My config: Windows 10 x64, chromecast 2 video.

The App recognize the chromecast, I can select an audio rate (mp3 or flac) but when it starts streaming, the only sound I can hear is a kind of white noise. Do you have an idea why?
Is there a way to log what happens?

Tell me if I can help you fixing the issue, because it's the perfect App for me!

Regards

**Comment by melchor629** [comment]
Hi, the implementation for capturing audio in Windows is really bad. I have started working in a new version that will have better support for Windows (and mac) for capturing audio. I will tell you more in some hours, or maybe in two or three days. Depending on how fast I can _fix_ that.

Thanks for posting the issue.

**Comment by melchor629** [comment]
Well, I think I managed to make a good implementation for Windows using a third party library. And I think I managed to make electron load the library correctly.

So, if you can kindly test this build, I would be grateful if you do :) Currently I cannot use my Chromecast Audio due to limitation on the WiFi network.

The test build: https://drive.google.com/file/d/1_OVFx1bocIT7Uqn3ADJbBb5rV3WaZwlz/view?usp=sharing

I made some tests by capturing my mic on Windows 10 and everything went well. So I think this build should fix the white noise problem. Tell me if it does, and I will make a new version.

**Comment by resom78** [comment]
It works like a charm now!!
Thanks a lot for your reactivity!
Another little thing: do you think there's a way to reduce the latency when playing?
Maybe if you stream 'wav' instead of 'flac' it could help? Or is it due to the chromecast buffer?

**Comment by melchor629** [comment]
I though about that many times... The latency is due to the buffering in the Chromecast. It is comparable to a radio streaming on the internet, you see a buffering there when you start listening. And a `wav` streaming is worse than a `flac` o `mp3` stream, I'm sure about that (introduces even more latency).

The only thing that could effectively reduce the latency is make an app for the Chromecast that manages the buffering and the playing itself. This way, the latency will be reduced. Although, currently I have no time to experiment with that. Maybe one day I could make it.

But for me, that latency is not very problematic. It is a little annoying. Despite the latency, the app is working quite well.

Anyway, thanks for the (positive) response. I will update the app with the new version.
